# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
    cmake_test_image:
        type: string
        default: knknkn1162/cmake_test:ubuntu_focal

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: docker login
                command: |
                    echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
            - run:
                name: docker build
                command: |
                    docker build -t << pipeline.parameters.cmake_test_image >> .
            - run:
                name: docker push
                command: |
                    docker push << pipeline.parameters.cmake_test_image >>
    test:
        docker:
            - image: << pipeline.parameters.cmake_test_image >>
              auth:
                  username: ${DOCKERHUB_USER}
                  password: ${DOCKERHUB_PASSWORD}
        working_directory: /app
        steps:
            - checkout
            - run:
                name: make and make install
                command: |
                    mkdir -p build
                    cd build
                    cmake ..
                    make build
                    make install install_external1 install_external2
            - run:
                name: `make install` check
                command:
                    find lib -type f | diff - ./tests/lib_check.txt
            - run:
                name: upload
                command: |
                    mkdir -p /tmp/artifacts
                    cp -r ./build/lib /tmp/artifacts
            - store_artifacts:
                path: /tmp/artifacts

workflows:
    build:
        jobs:
            - build:
                context:
                    - dockerhub
            - test:
                requires:
                    - build
                context:
                    - dockerhub
