# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
    cmake_test_image:
        type: string
        default: knknkn1162/cmake_test:ubuntu_focal

jobs:
    build:
        machine: true
        steps:
                name: docker login
                command: |
                    echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
            - run:
                name: docker build
                command: |
                    docker build -t << pipeline.parameters.cmake_test_image >> .
            - run:
                name: docker push
                command: |
                    docker push << pipeline.parameters.cmake_test_image >> .
